service: nest-postgresql-1

plugins:
  - serverless-localstack
  - serverless-offline

custom:
  serverless-offline:
    useChildProcesses: true
  localstack:
    #debug: true
    stages: [local]
    host:  http://localstack
    edgePort: 4566 


provider:
  name: aws
  runtime: nodejs18.x

package:
  exclude:
    - node_modules/**

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'