service: nest-postgresql-1

plugins:
  - serverless-localstack
  - serverless-offline

custom:
  serverless-offline:
    useChildProcesses: true
  localstack:
    #debug: true
    stages: [local]
    host:  http://localstack
    edgePort: 4566 


provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  memorySize: 512
  timeout: 30

package:
  exclude:
    - node_modules/**
    - test/**
    - src/**
    - .devcontainer/**

functions:
  main:
    handler: dist/src/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'